stages:
  - build
  - deploy

build_job:
  before_script:
    - cd ${CI_PROJECT_DIR}
    - rm -fr build/*
  stage: build
  tags: [layout]
  artifacts:
    name: "${CI_PROJECT_NAME}-${CI_JOB_NAME}-${CI_COMMIT_SHORT_SHA}"
    paths:
      - build/
    expire_in: 1 week
  script:
    - cd ${CI_PROJECT_DIR}
    - npm install
    - npm run ${npm_action}

deploy_job:
  stage: deploy
  tags: [layout]
  before_script:
    - if [ ! -d "/home/layout/public_html.${CI_PROJECT_NAME}-layout" ]; then mkdir -p "/home/layout/public_html.${CI_PROJECT_NAME}-layout"; else rm -fr "/home/layout/public_html.${CI_PROJECT_NAME}-layout"/*; fi
  dependencies:
    - build_job
  script:
    - cd ${CI_PROJECT_DIR}
    - mv build/* "/home/layout/public_html.${CI_PROJECT_NAME}-layout/"
    - cowsay -f tux.cow "Layout was sucessfully deployed to http://${CI_PROJECT_NAME}.layout/"
